### ISSUE TITLE
蛋壳salt

### ISSUE THREAD

**Issue by auroralzone** [gadfly0x/signature_algorithm#12]
请教大佬，请问salt是怎么生成的？

**Comment by gadfly0x** [comment]
代码里面有啊，sign_with_query_items函数

**Comment by auroralzone** [comment]
是的，看到了！蛋壳salt是固定的吗？还是用什么加密形成的？（如：网易翻译是，时间戳+随机数）

**Comment by gadfly0x** [comment]
你看代码，有写的。你的编程语言是什么？你是看不太懂python吗？

**Comment by auroralzone** [comment]
salt = 'R2UJE2UNhINnvjfaVPEC7FM8aUBoRVmgtv0zAhAD'
这个值是永久固定的？
我用Python的

**Comment by gadfly0x** [comment]
盐是固定的

**Comment by gadfly0x** [comment]
我明白了你的疑惑。变量重名了，导致了你的误解。下面的变量应该是叫sign，不是salt。我已经改了。你再看看，就明白了

**Comment by auroralzone** [comment]
好的，非常感谢大佬(这位大佬很热心，很nice)
