### ISSUE TITLE
自如des解密太慢了，有没有别的办法

### ISSUE THREAD

**Issue by aming-zi** [gadfly0x/signature_algorithm#15]

**Comment by gadfly0x** [comment]
你换个加解密的库，代码里面用的是pyDes，你可以换成pycrypto，这个速度快。之后我也会更新成pycrypto。

**Comment by gadfly0x** [comment]
已将pyDes改成pycryptodome，提升了加解密速度。简单测试了一下使用pyDes包100次加解密大概需要3秒，pycryptodome只需要0.016秒
