### ISSUE TITLE
nga的登录签名算法能帮忙逆向一下吗?

### ISSUE THREAD

**Issue by Liloupar** [gadfly0x/signature_algorithm#2]
之前搞了很久没彻底搞定.
下载链接:http://app.nga.cn/

逻辑在一个sign的so文件里,有个jni方法...
ida实在看不懂里面怎么签名的

**Comment by imvmi** [comment]
正好看见了，花了一个半小时折腾下，jni里那个方法的算法的伪代码是这个
没写代码验证，只是静态分析了下，不保证正确性，不过八九不离十
a = <apk的32位签名>;    //packageinfo.signatures[0].toCharsString()
b = <要加密的字符串>;
c = <ida里以12d6a开头的那串32位字符串>;
result = MD5( MD5(a+b)+c);

**Comment by Liloupar** [comment]
@ThreeGold127 我试一下 谢谢了

**Comment by Liloupar** [comment]
@ThreeGold127 
我测试了一下和调用jni方法生成出来的不一致...
不过还是谢谢啦

**Comment by ThreeGold127** [comment]
> @ThreeGold127
> 我测试了一下和调用jni方法生成出来的不一致...
> 不过还是谢谢啦

如果你说的是app_api.php接口里的sign字段的话，这个字段没用到jni里的方法，它的算法是
MD5( appid + access_uid + access_token + access_uid + t + "392e916a6d1d8b7523e2701470000c30bc2165a1")
这几个字段appid、access_uid、access_token、access_uid 、t都是请求里能找见的

**Comment by Liloupar** [comment]
@ThreeGold127 
不是的 我说的就是jni里面的那个方法
传递一个context和一个时间戳的那个

**Comment by Liloupar** [comment]
@ThreeGold127 
我指的是so里面的那个getMD5KeyFormJNI	
```
public static native String getMD5KeyFormJNI(Context paramContext, String paramString);
```

接口请求的那个我已经搞定了.这个是登录的时候用的,登录的时候会调用一个js桥接方法,这个时候需要返回一个计算出来的签名,其中要用到这个jni方法

谢谢大佬了

**Comment by imvmi** [comment]
你试试这个，我可能看漏了个MD5加密
result = MD5( MD5( MD5(a) +b)+c);

**Comment by Liloupar** [comment]
@ThreeGold127 
嗯我验证下 谢啦

**Comment by Liloupar** [comment]
@ThreeGold127 
MD5( MD5( MD5("9adecde86691f56d3eea4b55f2684526"签名) +时间戳)+"12d6af9da0f1fe4e3c87f76ce0aec149")

与jni方法的那个还是不一致

T.T

**Comment by imvmi** [comment]
给个时间戳，和实际的签名结果，我研究研究

**Comment by Liloupar** [comment]
@ThreeGold127 
时间戳 1567414843
so计算出的结果 b67037d30c868e231f0e2ad4d615a05e
我计算出的结果 c89cee665fc11c9579d411c0fba87221(MD5( MD5( MD5(a) +b)+c))

keystone签名 9adecde86691f56d3eea4b55f2684526
so中的字符串 12d6af9da0f1fe4e3c87f76ce0aec149

我采用的md5算法

```
 try {
            byte[] digest = MessageDigest.getInstance("MD5").digest(str.getBytes("UTF-8"));
            StringBuilder stringBuilder = new StringBuilder(digest.length * 2);
            for (byte b : digest) {
                if ((b & 255) < 16) {
                    stringBuilder.append("0");
                }
                stringBuilder.append(Integer.toHexString(b & 255));
            }
            return stringBuilder.toString();
        } catch (Throwable e) {
            throw new RuntimeException("Huh, MD5 should be supported?", e);
        }
```

**Comment by imvmi** [comment]
研究半天，感觉 MD5( packageinfo.signatures[0].toCharsString() ) ，和app签名里的那个MD5值好像还不一样

**Comment by imvmi** [comment]
果然不一样，packageinfo.signatures[0].toCharsString() 的值是下面这个东西

`308201ff30820168a00302010202044f33bca7300d06092a864886f70d01010505003044310b30090603550406130238363110300e060355040813076265696a696e673110300e060355040713076265696a696e673111300f0603550403130866656e67726f6e67301e170d3132303230393132333133355a170d3432303230313132333133355a3044310b30090603550406130238363110300e060355040813076265696a696e673110300e060355040713076265696a696e673111300f0603550403130866656e67726f6e6730819f300d06092a864886f70d010101050003818d0030818902818100b1890dcdb61a60f4ff4e0eef5389f846aa1ed903111353c13e95b05db63032bb612479496f28a8d1bba4724a62740d4043aa642d97726dc55642965e776b69071f0ecd8452921e9586520b495bd2f40d6fdb68f56790876c385e8d2931e5c158254d68c23957d2b543a24f858d943c7f50216897c311da4cb51abae2ce99fc270203010001300d06092a864886f70d0101050500038181000eedfbe364d78a68959da2ece2cf4bddf2634ef0d5b579333a3f7e6d613537cbad947a8e619427ed9225dcb4519622a8b64007fe6098852ac06e34dee3d453977f14472744d82ebf3cba3bb5ea9c4a393aa32cc94f71872db508b1b2b4baa99e4765dfc28cf6eab1a5b4ab6d5c31e53c07368900922d9f46712a696ac32fb923`

这玩意的MD5是 161c8c015f912abf4434c3263279c296

MD5( MD5( “161c8c015f912abf4434c3263279c296”+时间戳)+"12d6af9da0f1fe4e3c87f76ce0aec149")
这个就对了

**Comment by Liloupar** [comment]
@ThreeGold127
太感谢了。
来个支付方式啥的，请大佬喝杯咖啡😄

**Comment by imvmi** [comment]
没必要啦，能从V站看到这个issue也不容易，都是缘分，哈哈

**Comment by Liloupar** [comment]
@ThreeGold127
好吧 那就说句谢谢啦
