### ISSUE TITLE
app版本问题

### ISSUE THREAD

**Issue by createalltheworld** [gadfly0x/signature_algorithm#4]
大佬你好，请教一下小红书app，请问一下你破解是的哪个版本的app？为什么我现在登陆小红书总是提示版本过低

**Comment by gadfly0x** [comment]
6.0，最新的也是一样的。小红书一直有检测的，检测到越狱、root、虚拟机等都会提示版本过低。

**Comment by createalltheworld** [comment]
好的，谢谢！

发自我的 iPhone
